---
- hosts: all
  become: yes
  gather_facts: true
  vars_files:
  - vars/main.yml
  roles:
  - { role: jenkins-nfs-vol-setup, when: jenkins_masters is defined }
  - { role: jenkins-ha-setup, when: jenkins_primary is defined }
  - { role: jenkins-ha-setup, tags: ["primary","standby"], when: jenkins_standby is defined }
  - { role: opc-config, when: jenkins_opc is defined }
