---
- hosts: all
  gather_facts: true
  become: yes
  tasks:
  - name: Get the cert from an RDP port
    community.crypto.get_certificate:
      host: "18.219.154.173"
      port: 8888
    run_once: true
    register: cert
    delegate_to: localhost
