---
#- name: Start and enable openssh server
#  service:
#    name: '{{ sshd_service_name }}'
#    state: started
#    enabled: true
#  become: true

- name: Install initial dependencies.
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ dependent_pkgs }}"

- name: Create a group for jenkins user
  group:
    name: '{{ slave_linux_jenkins_username }}'
    state: present
  become: true

- name: Create jenkins user with root privileges
  user:
    name: '{{ slave_linux_jenkins_username }}'
    group: '{{ slave_linux_jenkins_username }}'
    password: '{{ slave_linux_jenkins_password }}'
    state: present
#    append: true
    createhome: true
  become: true

- name: Set authorized key
  authorized_key:
    user: '{{ slave_linux_jenkins_username }}'
    state: present
    key: '{{ slave_linux_jenkins_public_key }}'
  become: true
  when: slave_linux_jenkins_public_key | trim

- name: Create slave home directory
  file:
    path: '{{ slave_linux_home }}'
    state: directory
    owner: '{{ slave_linux_jenkins_username }}'
    group: '{{ slave_linux_user_group }}'
    mode: 0775
  become: true

- name: Install slave jenkins agent
  jenkins_script:
    user: '{{ jenkins_admin_username }}'
    password: '{{ jenkins_admin_password }}'
    validate_certs: false
    timeout: 120
    url: "http://{{ hostvars[groups['jenkins_primary'][0]]['ansible_eth0']['ipv4']['address'] }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}"
    script: >-
      {{ lookup('template', 'add_linux_slave.groovy.j2') }}

#- name: Add selinux support
 # include_tasks: selinux-support.yml
 # when: ansible_os_family == 'RedHat'
