    - name: Ensure NFS is installed.
      package: "name={{ nfs_package }} state=installed"

   # - name: Creating jenkins home directory
   #   file:
   #    path: /mnt/var/lib/cloudbees-core-cm
   #    state: directory


#    - name: Ensure mount directory exists.
#      file:
#        path: "{{ efs_mount_dir }}"
#        state: directory
#        mode: 0755

    - name: Get current AZ from AWS.
      uri:
        url: http://169.254.169.254/latest/meta-data/placement/availability-zone
        return_content: yes
      register: aws_current_az

    - name: Ensure EFS volume is mounted.
      mount:
        name: "/mnt{{ efs_mount_dir }}"
        src: "{{ aws_current_az.content }}.{{ efs_file_system_id }}.efs.{{ aws_region }}.amazonaws.com:/"
        fstype: nfs
        opts: nfsvers=4.1
        state: mounted
    #- name: Remove the files exist in efs filesystem
    #  file:
    #   path: "/mnt/{{ efs_mount_dir }}"
    #   state: absent

    # Print the contents of the mount to the log.
    - command: ls -lah /mnt"{{ efs_mount_dir }}"
      register: efs_contents
    - debug: var=efs_contents
